# Generated by Django 4.2.7 on 2024-05-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='proof',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
