# Generated by Django 4.2.7 on 2024-05-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cApp', '0002_users_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
