# Generated by Django 5.0.6 on 2024-05-15 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cApp', '0003_users_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cApp.users'),
        ),
    ]
