# Generated by Django 5.0.6 on 2024-05-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cApp', '0004_alter_analysis_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='img',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
