# Generated by Django 5.0.6 on 2024-05-17 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cApp', '0005_alter_analysis_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='aadhar',
        ),
        migrations.RemoveField(
            model_name='users',
            name='address',
        ),
        migrations.RemoveField(
            model_name='users',
            name='proof',
        ),
        migrations.AddField(
            model_name='users',
            name='building_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='department',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='designation',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='district',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='pincode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='street',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ChatAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=200)),
                ('sender', models.CharField(max_length=20)),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cApp.users')),
            ],
        ),
        migrations.CreateModel(
            name='CrimeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('crimetype', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
                ('distict', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=500)),
                ('date_reported', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('report', models.FileField(null=True, upload_to='')),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cApp.users')),
            ],
        ),
    ]
