# Generated by Django 5.0.6 on 2024-05-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cApp', '0006_remove_users_aadhar_remove_users_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimefile',
            name='date_reported',
            field=models.DateField(),
        ),
    ]
