# Generated by Django 5.0.6 on 2024-05-18 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cApp', '0007_alter_crimefile_date_reported'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crimefile',
            old_name='distict',
            new_name='district',
        ),
    ]
