# Generated by Django 5.0.6 on 2024-05-18 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cApp', '0008_rename_distict_crimefile_district'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CrimeFile',
        ),
    ]
