# Generated by Django 5.0.6 on 2024-05-18 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cApp', '0011_delete_crimefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('date_reported', models.DateField()),
                ('crimetype', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
                ('district', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('report', models.FileField(null=True, upload_to='')),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cApp.users')),
            ],
        ),
    ]
