# Generated by Django 5.0.6 on 2024-05-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cApp', '0012_crimefiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimefiles',
            name='crimeno',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
